### ISSUE TITLE
Provide a straightforward way to burn another drive without having to restart the program

### ISSUE THREAD

**Issue by jviotti** [resin-io/herostratus#41]

**Comment by taahirisaacs** [comment]
![screen shot 2015-11-30 at 11 03 18 am](https://cloud.githubusercontent.com/assets/15251376/11474412/a4fae134-9780-11e5-8d04-a7e85b432378.png)

**Comment by jviotti** [comment]
As a note, we should extend this new screen to notify the user that he can eject the drive without needing to safely remove from the operating system (that's already done by the app).
